version: '3.4'

services:
  contosouniversity:
    container_name: contosoContainer
    image: ${DOCKER_REGISTRY-}contosouniversity
    build:
      context: .
      dockerfile: ContosoUniversity\Dockerfile

  sql-server-db:
    container_name: sql-server-db
    image: microsoft/mssql-server-windows-developer
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Mussolin26"
      ACCEPT_EULA: "Y"
